

const Banner = () => {
    return (
        <div className="my-20">
            <h2>i am home from component</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus dolorum a at facere omnis hic illo molestiae ea porro, velit deleniti sint quaerat unde libero quo maxime ut nulla quam iusto? Perferendis dolorem animi debitis deserunt, culpa dolorum blanditiis aspernatur molestias, soluta quibusdam alias est sed praesentium! Deserunt, possimus quaerat autem accusamus eum rem praesentium placeat, voluptatum aut quo vitae, et saepe cum excepturi alias laborum porro molestiae maiores amet nemo. Consectetur iure tenetur quibusdam reiciendis excepturi incidunt sint voluptatibus eveniet sapiente consequatur. Blanditiis fugiat quam recusandae saepe quis libero exercitationem, necessitatibus illum placeat aperiam numquam rerum, consectetur corrupti ad aut? Molestiae explicabo doloremque cum sint, culpa fugit earum at ipsa accusamus voluptatem iusto vero maxime facilis. Quod temporibus quasi, qui cupiditate laboriosam doloremque provident consequatur, voluptatibus error recusandae accusamus, modi eaque. Repellendus et ratione eaque in, omnis, sint alias animi magni soluta numquam dolore voluptate. Unde a quae ratione quis necessitatibus impedit laboriosam quo tenetur repudiandae, consequatur libero neque, illum ex cumque minima eum amet vel enim officiis. Voluptatem fugiat odio nesciunt incidunt ratione corrupti libero cumque saepe natus debitis expedita ea rerum odit veniam accusamus magni iure ab, nemo ducimus. Soluta, tempora. Dicta, laborum neque? Optio, vitae? Dignissimos?</p>
            <h2>i am home from component</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus dolorum a at facere omnis hic illo molestiae ea porro, velit deleniti sint quaerat unde libero quo maxime ut nulla quam iusto? Perferendis dolorem animi debitis deserunt, culpa dolorum blanditiis aspernatur molestias, soluta quibusdam alias est sed praesentium! Deserunt, possimus quaerat autem accusamus eum rem praesentium placeat, voluptatum aut quo vitae, et saepe cum excepturi alias laborum porro molestiae maiores amet nemo. Consectetur iure tenetur quibusdam reiciendis excepturi incidunt sint voluptatibus eveniet sapiente consequatur. Blanditiis fugiat quam recusandae saepe quis libero exercitationem, necessitatibus illum placeat aperiam numquam rerum, consectetur corrupti ad aut? Molestiae explicabo doloremque cum sint, culpa fugit earum at ipsa accusamus voluptatem iusto vero maxime facilis. Quod temporibus quasi, qui cupiditate laboriosam doloremque provident consequatur, voluptatibus error recusandae accusamus, modi eaque. Repellendus et ratione eaque in, omnis, sint alias animi magni soluta numquam dolore voluptate. Unde a quae ratione quis necessitatibus impedit laboriosam quo tenetur repudiandae, consequatur libero neque, illum ex cumque minima eum amet vel enim officiis. Voluptatem fugiat odio nesciunt incidunt ratione corrupti libero cumque saepe natus debitis expedita ea rerum odit veniam accusamus magni iure ab, nemo ducimus. Soluta, tempora. Dicta, laborum neque? Optio, vitae? Dignissimos?</p>
            <h2>i am home from component</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus dolorum a at facere omnis hic illo molestiae ea porro, velit deleniti sint quaerat unde libero quo maxime ut nulla quam iusto? Perferendis dolorem animi debitis deserunt, culpa dolorum blanditiis aspernatur molestias, soluta quibusdam alias est sed praesentium! Deserunt, possimus quaerat autem accusamus eum rem praesentium placeat, voluptatum aut quo vitae, et saepe cum excepturi alias laborum porro molestiae maiores amet nemo. Consectetur iure tenetur quibusdam reiciendis excepturi incidunt sint voluptatibus eveniet sapiente consequatur. Blanditiis fugiat quam recusandae saepe quis libero exercitationem, necessitatibus illum placeat aperiam numquam rerum, consectetur corrupti ad aut? Molestiae explicabo doloremque cum sint, culpa fugit earum at ipsa accusamus voluptatem iusto vero maxime facilis. Quod temporibus quasi, qui cupiditate laboriosam doloremque provident consequatur, voluptatibus error recusandae accusamus, modi eaque. Repellendus et ratione eaque in, omnis, sint alias animi magni soluta numquam dolore voluptate. Unde a quae ratione quis necessitatibus impedit laboriosam quo tenetur repudiandae, consequatur libero neque, illum ex cumque minima eum amet vel enim officiis. Voluptatem fugiat odio nesciunt incidunt ratione corrupti libero cumque saepe natus debitis expedita ea rerum odit veniam accusamus magni iure ab, nemo ducimus. Soluta, tempora. Dicta, laborum neque? Optio, vitae? Dignissimos?</p>
        </div>
    );
};

export default Banner;